---
- name: Basic VM setup
  hosts: proxmox_all_running
  gather_facts: false
  become: true
  become_method: sudo
  become_user: root
  strategy: free

  vars:
    ad_username: "{{ lookup('env', 'AD_USERNAME') }}"
    ad_password: "{{ lookup('env', 'AD_PASSWORD') }}"
    join_realm: OAK.HOME
    join_domain: oak.home
    join_server: "10.1.0.220"

  tasks:
    - name: LXC bootstrapping
      when: proxmox_vmtype == "lxc"
      ansible.builtin.include_role:
        name: lxc_ssh_setup

    - name: manually gather facts
      ansible.builtin.setup:

    - name: Unix setup
      when: proxmox_ostype != 'windows'
      block:
      #### installations  ####
        - name: Install basics
          ansible.builtin.package:
            name:
              - vim
              - tmux
              - curl


      #### identities ####
        - name: Add groups
          loop_control:
            loop_var: group
          ansible.builtin.group:
            name: "{{ group.name }}"
            gid: "{{ group.gid }}"
            state: present
          loop:
            - name: media-managers
              gid: 421


        - name: Add users
          loop_control:
            loop_var: user
          ansible.builtin.user:
            name: "{{ user.name }}"
            comment: Ansible created
            uid: "{{ user.uid }}"
            groups: "{{ user.groups | default(omit) }}"
            create_home: "{{ user.create_home }}"
            shell: "{{ user.shell | default('/bin/bash') }}"
            ssh_public_key: "{{ user.pubkey | default(omit) }}"
            state: present
            append: true
          loop:
            - name: automation
              uid: 1007
              groups: media-managers
              create_home: false


      #### domain join ####
        - name: Domain join
          ansible.builtin.include_role:
            name: linux_joindomain

          vars:
            Join_User: "{{ ad_username }}"
            DomainName: "{{ join_domain }}"
            Join_User_Pass: "{{ ad_password }}"
            realm: "{{ join_realm }}"
            server: "{{ join_server }}"
