---
- name: Basic VM setup
  hosts: proxmox_all_running
  vars:
    ad_username: "{{ lookup('env', 'AD_USERNAME') }}"
    ad_password: "{{ lookup('env', 'AD_PASSWORD') }}"

  tasks:

    #### installations  ####
    - name: Install basics
      ansible.builtin.package:
        name:
          - vim
          - tmux
          - curl


    #### identities ####
    - name: Add groups
      loop_control:
        loop_var: group
      ansible.builtin.group:
        name: "{{ group.name }}"
        gid: "{{ group.gid }}"
        state: present
      loop:
        - name: media-managers
          gid: 421


    
    - name: Add users 
      loop_control:
        loop_var: user
      ansible.builtin.user:
        name: "{{ user.name }}"
        comment: Ansible created
        uid: "{{ user.uid }}"
        groups: "{{ user.groups | default(omit) }}"
        create_home: "{{ user.create_home }}"
        shell: "{{ user.shell | default('/bin/bash') }}"
        ssh_public_key: "{{ user.pubkey | default(omit) }}"
        state: present
        append: yes

      loop:
        - name: automation
          uid: 1007
          groups: media-managers
          create_home: no


